language: node_js

node_js:
  - node

addons:
  ssh_known_hosts: gendercomics.net

before_install:
  - openssl aes-256-cbc -K $encrypted_ac25a508ad54_key -iv $encrypted_ac25a508ad54_iv -in deploy-key.enc -out deploy-key -d

install:
  - yarn install

script:
  - yarn build

#after_success:
#- eval "$(ssh-agent -s)"
#- chmod 600 deploy-key
#- ssh-add deploy-key
#- cd $TRAVIS_BUILD_DIR/public
#- scp -r * deploy@gendercomics.net:/var/gendercomics/web/

dist: trusty
sudo: false

