language: node_js

node_js:
  - node

dist: trusty
sudo: false

addons:
  ssh_known_hosts: gendercomics.net

cache:
  directories:
    - node_modules

before_install:
  - openssl aes-256-cbc -K $encrypted_ac25a508ad54_key -iv $encrypted_ac25a508ad54_iv -in deploy-key.enc -out deploy-key -d

install:
  - yarn

before_script:
  - npm i -g gatsby-cli
  - VERSION=$(node -p -e "require('./package.json').version")

script:
  - yarn build
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t gendercomics/website .
  - docker tag gendercomics/website gendercomics/website:latest
  - docker tag gendercomics/website gendercomics/website:$VERSION
  - docker images
  - docker push gendercomics/website:latest
  - docker push gendercomics/website:$VERSION

#after_success:
# - eval "$(ssh-agent -s)"
#  - chmod 600 deploy-key
#  - ssh-add deploy-k
#  - cd $TRAVIS_BUILD_DIR/public
#  - scp -r * deploy@gendercomics.net:/var/gendercomics/website/public

before_deploy:
  - openssl aes-256-cbc -K $encrypted_ac25a508ad54_key -iv $encrypted_ac25a508ad54_iv -in deploy-key.enc -out deploy-key -d
  - eval "$(ssh-agent -s)"
  - chmod 600 deploy-key
  - ssh-add deploy-key

deploy:
  - provider: script
    skip_cleanup: true
    script: ssh deploy@gendercomics.net 'docker pull gendercomics/website:latest && cd /var/gendercomics/docker && docker-compose up -d gendercomics-website-stage'
    on:
      all_branches: true
  - provider: script
    skip_cleanup: true
    script: ssh deploy@gendercomics.net 'docker pull gendercomics/website:1.1.0 && cd /var/gendercomics/docker && docker-compose up -d gendercomics-website'
    on:
      branch: master

notifications:
  slack:
    rooms:
      - visualitiesofgender:3zAI6z6JJXLeEIaBU49O0Wkr#website
    on_success: change # default: always
    on_failure: always # default: always
  email:
    recipients:
      - michael.litschauer@gmail.com
    on_success: always
    on_failure: always
