version: '3'

services:

  gendercomics-website-stage:
    image: gendercomics/website:latest
    container_name: gendercomics-website-stage
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - traefik.frontend.rule=Host:stage.${HOST}
      - traefik.port=80
      - traefik.frontend.auth.basic=gesche:$$apr1$$MAPCYH7m$$8wTgBxTOH731kXK3fo1JC/
      - traefik.docker.network=proxy

  gendercomics-website:
    image: gendercomics/website:1.1.4
    container_name: gendercomics-website
    restart: always
    networks:
      - proxy
    labels:
      - traefik.frontend.rule=Host:${HOST}
      - traefik.port=80
      - traefik.docker.network=proxy

networks:
  proxy:
    external: true
